version: '3'

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: ${APP_NAME:?err}-php
    volumes:
      - .:/var/www/html/:cached
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "PHPSTORM"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9008 start_with_request=yes"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME:?err}-nginx
    links:
      - 'php'
    volumes:
      - .:/var/www/html/
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "8019:80"

###> doctrine/doctrine-bundle ###
  db:
    image: mariadb
    container_name: ${APP_NAME:?err}-db
    restart: always
    ports:
      - "127.0.0.1:3319:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/my.cnf
      - ./docker/db:/docker-entrypoint-initdb.d
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "1000"
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###

networks:
  default:
    driver: bridge